import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Header from '../component/header'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fitnee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <div className="children">{children}</div>
        <footer>Copyright @Fitnee All Rights Reserved</footer>
      </body>
    </html>
  );
}
