import "./globals.css";
// import { Inter } from "next/font/google";
import Link from "next/link";
import Header from '../component/header'
import Footer from "@/component/footer";
import localFont from 'next/font/local'

const myFont = localFont({ 
  src: [
    {
      path: '../public/font/Pretendard-Thin.woff2',
      weight: '300',
    },
    {
      path: '../public/font/Pretendard-Regular.woff2',
      weight: '400',
    },
    {
      path: '../public/font/Pretendard-Medium.woff2',
      weight: '500',
    },
    {
      path: '../public/font/Pretendard-SemiBold.woff2',
      weight: '600',
    },
    {
      path: '../public/font/Pretendard-Bold.woff2',
      weight: '700',
    },
  ],
 })

export const metadata = {
  title: "Fitnee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <Header/>
        <div className="children">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
